from time import sleep
# region Declaració de funcions
def recopilar_ingredients():
    print('1.Recopilar ingredients')
    sleep(0.5)
    print('\tComprar al supermercat.')
    print('\tDisposar sobre el marbre.')
    sleep(0.5)
def cuinar_tallarines():
    print('2.Cuinar tallarines')
    sleep(0.5)
    print('\tPreparar aigua.')
    print('\t\tEscalfar aigua.')
    print('\t\tPosar-hi sal.')
    sleep(0.5)
    print('\tBullir tallarines.')
    print('\tEscórrer tallarines.')
    print('\tDeixar-les preparades.')
    sleep(0.5)
def cuinar_pastanagues():
    print('3.Cuinar pastanagues')
    sleep(0.5)
    print('\tTallar pastanagues.')
    print('\tFregir pastanagues.')
    sleep(0.5)
    print('\t\tPreparar paella per fregir.')
    print('\t\tRossejar pastanagues.')
    print('\t\tNetejar oli de paella.')
    sleep(0.5)
    print('\tDeixar pastanagues preparades.')
    sleep(0.5)
def cuinar_cebes():
    print('4.Cuinar cebes')
    sleep(0.5)
    print('\tTallar cebes.')
    print('\tFregir cebes.')
    sleep(0.5)
    print('\t\tPreparar paella per fregir.')
    print('\t\tRossejar cebes.')
    print('\t\tNetejar oli de paella.')
    sleep(0.5)
    print('\tDeixar cebes preparades.')
    sleep(0.5)
def preparacio_final():
    print('5.Preparació final')
    sleep(0.5)
    print('\tBarrejar cebes.')
    print('\tSaltar ingredients.')
    sleep(0.5)
    print('\t\tPreparar paella per saltar.')
    print('\t\tCuinar remenant ingredients.')
    print('\tDeixar llest per servir.')
# endregion
# region main
recopilar_ingredients()
cuinar_tallarines()
cuinar_pastanagues()
cuinar_cebes()
preparacio_final()
# endregion